### PR TITLE
Feature/query extention

### PR DESCRIPTION
**Pull request by Sushovan861**
Extending the Odata server's query and refactoring the pruning based out of Odata Specification

http://docs.oasis-open.org/odata/odata-json-format/v4.0/os/odata-json-format-v4.0-os.html#_Toc372793040

### CODE REVIEW

**Comment by pofider** [comment]
Thank you for your time on this! I've reviewed the code and it looks great.

However, would you consider adding some tests to [odataServerTest.js](https://github.com/pofider/node-simple-odata-server/blob/master/test/odataServerTest.js) covering your additions? It should take you just short time. Thank you again.

**Comment by Sushovan861** [comment]
@pofider Thanks for your comments. I have incorporated the tests factoring my changes in this PR.

**Comment by pofider** [comment]
Wonderful work, thank you. I will update dependencies and release it today.

**Comment by pofider** [comment]
released in 0.3.0

**Pull request merged**
